### PR TITLE
Solution for 11683

### PR DESCRIPTION
**Pull request by deepampriyadarshi**
Do check it when you free

### CODE REVIEW

**Review by Ryednap — APPROVED** [review]
Nice code :- Just a note that have you analyzed it's complexity ? . Actually O(n) where n = |x0| . A similar question is for the sum of the digit's and it's compleixty is actually even smaller so you may be string of size greater than even 10 million. But the same recursion works as after small work around we can still bring the compleixty to O(1million) or O(10 mill).

**Review by Ryednap — APPROVED** [review]
Yeah fine

**Comment by deepampriyadarshi** [comment]
> Nice code :- Just a note that have you analyzed it's complexity ? . Actually O(n) where n = |x0| . A similar question is for the sum of the digit's and it's compleixty is actually even smaller so you may be string of size greater than even 10 million. But the same recursion works as after small work around we can still bring the compleixty to O(1million) or O(10 mill).

Yeah one work around came to my mind while solving but I don't know why I didn't implement it (maybe i thought of keeping it a general solution). We can remove the recursive function **since the  ans ranges from [1,4]**  and use **if-else statements**. Also instead of `length() `function we can use `floor(log10(n) + 1);`

**Comment by deepampriyadarshi** [comment]
@Ryednap  Did you check commit [https://github.com/Ryednap/Contest/pull/1/commits/7bb90e318fe9576299dbd46c905adbd6eb0d9b85](url)

Solution for 11683

**Comment by Ryednap** [comment]
Do one thing make a folder of your name just like me first and then commit it to the main branch all fine

**Pull request merged**
